# Generated by Django 2.0.2 on 2018-02-22 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_remove_album_artists'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='melon_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='멜론 Album ID'),
        ),
        migrations.AlterField(
            model_name='album',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
