# Generated by Django 2.0.2 on 2018-02-28 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0003_auto_20180227_0713'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistYouTube',
            fields=[
                ('youtube_id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='YouTube ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
            ],
        ),
        migrations.AddField(
            model_name='artist',
            name='youtube_videos',
            field=models.ManyToManyField(blank=True, related_name='artists', to='artist.ArtistYouTube'),
        ),
    ]
