# Generated by Django 2.0.2 on 2018-02-28 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0005_artistyoutube_url_img_cover'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artistyoutube',
            old_name='url_img_cover',
            new_name='url_thumbnail',
        ),
    ]
